# 배열을 파일에 저장 및 불러오기
- ## 바이너리 파일로 저장/불러오기
    - ### np.save("파일경로", 배열)
        - 배열을 raw 바이너리 형식으로 저장한다. (압축하지 않은)
        - 파일명에 확장자로 npy를 붙인다. (무조건 붙인다. abc.xxx 해도 abc.xxx.npy 로 저장)
    - ### np.load("파일경로") 
        - 파일에 저장된 배열을 불러온다.
    - ### np.savez("파일경로", 이름=배열, 이름=배열, ...)
        - 여러개의 배열을 저장할 때 사용
        - 파일명에 확장자로 npz가 붙는다.
        - 내부적으로 압축해서 저장한다.
        - load() 함수로 불러오면 저장된 배열목록이 반환 된다. 저장시 지정한 이름을 이용해 조회 
- ## 텍스트 파일로 저장하고 불러오기
    - ### savetxt("파일경로", 배열 [, delimiter='공백') 
        - 텍스트 형태로 저장.
        - 각 원소는 공백을 기준으로 나뉘며 delimiter 속성으로 구분자를 지정할 수 있다. (delimiter생략시 공백)
        - 1차원과 2차원 배열만 저장 가능하다. (3차원 이상은 저장이 안된다.)
    - ### loadtxt("파일경로" [,dtype=float, delimiter=공백)

In [1]:
import numpy as np

In [2]:
a = np.array([1,10,5,7,20])
b = np.ones(shape = (3,3,5))
c = np.random.normal(10,2, size=(5,10))
print(a.shape, b.shape, c.shape)

(5,) (3, 3, 5) (5, 10)


In [3]:
#binary 파일에 배열을 저장
# 한파일에 하나의 배열 저장 - save(경로, 배열)
# 경로 : 상대 경로 / 절대 경로
np.save("new_dir/array_a", a)
np.save("new_dir/array_b.npy", b)
np.save("new_dir/array.c", c)

In [4]:
#불러오기(load) - Load
a2 = np.load('new_dir/array_a.npy')
b2 = np.load('new_dir/array_b.npy')
c2 = np.load('new_dir/array.c.npy')
print(a2, b2, c2)

[ 1 10  5  7 20] [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]] [[10.7038627  13.88291041 12.5942298   8.71956134  8.47441458  6.79524802
  10.59929534 13.23411595 13.46909517  9.53799973]
 [11.93456555  7.69155811 11.60238565 12.37780093 10.64567764  8.42520171
   8.33153623 14.19274849  8.39307698  6.89455053]
 [ 9.87290208 11.74379487  7.79599379  9.8077243   6.81725071  8.37521055
   7.66635887  8.69569845 12.51943736 12.5027761 ]
 [ 9.82015874 14.01817795 11.75903037  6.38757121  8.29739235  8.55049946
   9.68321717 10.00490429  9.44478431 10.29717024]
 [ 7.58297106  8.53215521  7.6814349   9.83104409 11.31498712  9.52077204
   9.8876127   3.92731077 10.3635461  11.0910163 ]]


In [5]:
# 한파일에 여러개 배열 - savez(경로, 이름1=배열, 이름2=배열, ...)
np.savez("new_dir/array", a_array = a, b_array = b, c_array = c)

In [6]:
arrays = np.load('new_dir/array.npz')
arrays

In [7]:
#배열들의 이름을 조회
arrays.files

['a_array', 'b_array', 'c_array']

In [8]:
# 각 배열을 조회 - index 연산자 사용
a3 = arrays['a_array']
b3 = arrays['b_array']
c3 = arrays['c_array']
a3

array([ 1, 10,  5,  7, 20])

In [9]:
b3.shape, c3.shape

((3, 3, 5), (5, 10))

In [10]:
#text파일로 저장 >> CSV. 1차원, 2차원 배열만 저장 가능
# savetxt(), Loadtxt()

In [11]:
np.savetxt('new_dir/a.csv', a)

In [15]:
a4 = np.loadtxt('new_dir/a.csv', dtype = np.int)

In [16]:
a4

array([ 1, 10,  5,  7, 20])

In [18]:
print(b.shape)
np.savetxt('new_dir/b.csv')   #1차원, 2차원만 저장 가능

(3, 3, 5)


TypeError: _savetxt_dispatcher() missing 1 required positional argument: 'X'

In [19]:
print(c.shape)
np.savetxt('new_dir/c.csv', c)

(5, 10)


In [20]:
np.savetxt('new_dir/c2.csv', c, delimiter=',')


In [21]:
c4 = np.loadtxt('new_dir/c.csv')
c4

array([[10.7038627 , 13.88291041, 12.5942298 ,  8.71956134,  8.47441458,
         6.79524802, 10.59929534, 13.23411595, 13.46909517,  9.53799973],
       [11.93456555,  7.69155811, 11.60238565, 12.37780093, 10.64567764,
         8.42520171,  8.33153623, 14.19274849,  8.39307698,  6.89455053],
       [ 9.87290208, 11.74379487,  7.79599379,  9.8077243 ,  6.81725071,
         8.37521055,  7.66635887,  8.69569845, 12.51943736, 12.5027761 ],
       [ 9.82015874, 14.01817795, 11.75903037,  6.38757121,  8.29739235,
         8.55049946,  9.68321717, 10.00490429,  9.44478431, 10.29717024],
       [ 7.58297106,  8.53215521,  7.6814349 ,  9.83104409, 11.31498712,
         9.52077204,  9.8876127 ,  3.92731077, 10.3635461 , 11.0910163 ]])

In [22]:
c5 = np.loadtxt('new_dir/c2.csv')

ValueError: could not convert string to float: '1.070386270116484084e+01,1.388291041158211492e+01,1.259422980420552740e+01,8.719561338993541355e+00,8.474414578444928736e+00,6.795248017577639743e+00,1.059929533814633018e+01,1.323411595114440331e+01,1.346909517005628310e+01,9.537999728104995967e+00'

In [24]:
c5 = np.loadtxt('new_dir/c2.csv', delimiter=',')
c5

array([[10.7038627 , 13.88291041, 12.5942298 ,  8.71956134,  8.47441458,
         6.79524802, 10.59929534, 13.23411595, 13.46909517,  9.53799973],
       [11.93456555,  7.69155811, 11.60238565, 12.37780093, 10.64567764,
         8.42520171,  8.33153623, 14.19274849,  8.39307698,  6.89455053],
       [ 9.87290208, 11.74379487,  7.79599379,  9.8077243 ,  6.81725071,
         8.37521055,  7.66635887,  8.69569845, 12.51943736, 12.5027761 ],
       [ 9.82015874, 14.01817795, 11.75903037,  6.38757121,  8.29739235,
         8.55049946,  9.68321717, 10.00490429,  9.44478431, 10.29717024],
       [ 7.58297106,  8.53215521,  7.6814349 ,  9.83104409, 11.31498712,
         9.52077204,  9.8876127 ,  3.92731077, 10.3635461 , 11.0910163 ]])

In [ ]:
c